Repository CS3103-Group10/exploitable-app, pull requests merged in 2020-10, with the labels that each got.

#3 init: setup client
  .editorconfig
  .gitignore
  .vscode/settings.json
  README.md
  client/.babelrc
  client/.eslintrc.js
  client/.prettierrc.js
  client/README.md
  client/next-env.d.ts
  client/next.config.js
  client/package.json
  client/src/layouts/TheLayout.tsx
  client/src/pages/_app.tsx
  client/src/pages/asiv/index.tsx
  client/src/pages/flora/index.tsx
  client/src/pages/flora/login/index.tsx
  client/src/pages/index.tsx
  client/src/styles/antd.less
  client/src/styles/app.css
  client/src/types/index.ts
  client/src/utils/index.ts
  client/tsconfig.json
  client/yarn.lock
  package.json
  ui/README.md
  ui/package.json
  ui/public/index.html
  ui/src/App.css
  ui/src/App.js
  ui/src/containers/HomePage.js
  ui/src/containers/LoginPage.js
  ui/src/containers/NotFoundPage.js
  ui/src/containers/ProtectedRoute.js
  ui/src/index.css
  ui/src/index.js
  ui/src/serviceWorker.js
  ui/yarn.lock
  yarn.lock
Labels: status: done, type: feature

#5 Backend: Add jwt token
  server/package-lock.json
  server/package.json
  server/src/routes/flora/users.ts
  server/src/services/jwt.ts
  server/yarn.lock
Labels: type: feature

#4 client: login integration
  client/src/pages/flora/login/index.tsx
  client/src/types/apiReqRes.ts
  client/src/types/index.ts
  client/src/types/models.ts
  client/src/utils/api/Route.ts
  client/src/utils/api/floraApi.ts
  client/src/utils/api/index.ts
  client/src/utils/index.ts
  server/src/errors/ApiError.ts
  server/src/errors/ApiErrorMessage.ts
  server/src/errors/index.ts
  server/src/middlewares/authHandler.ts
  server/src/middlewares/customErrorHandler.ts
  server/src/middlewares/index.ts
  server/src/models/Inventory.ts
  server/src/models/Product.ts
  server/src/models/User.ts
  server/src/models/index.ts
  server/src/routes/asiv/payment.ts
  server/src/routes/flora/products.ts
  server/src/routes/flora/users.ts
  server/src/services/jwt.ts
  server/src/services/server.ts
  server/src/utils/constants.ts
  server/src/utils/index.ts
Labels: status: done, type: feature

#6 feat: add persistent login session
  client/src/hooks/index.ts
  client/src/hooks/useAuth.tsx
  client/src/layouts/TheLayout.tsx
  client/src/pages/_app.tsx
  client/src/pages/asiv/index.tsx
  client/src/pages/flora/index.tsx
  client/src/pages/flora/login/index.tsx
  client/src/pages/index.tsx
  client/src/utils/api/Route.ts
  client/src/utils/api/floraApi.ts
  client/src/utils/api/index.ts
  client/src/utils/api/utils.ts
  server/src/routes/flora/users.ts
Labels: status: in progress, type: feature
