Repository CS3103-Group10/exploitable-app, pull requests merged in 2020-11, with the labels that each got.

#8 feat: add Asiv secure payments site feature
  client/src/hooks/useAuth.tsx
  client/src/pages/flora/index.tsx
  client/src/types/apiReqRes.ts
  client/src/utils/api/Route.ts
  client/src/utils/api/floraApi.ts
  client/src/utils/constants.ts
  client/src/utils/index.ts
  server/package-lock.json
  server/package.json
  server/src/errors/ApiErrorMessage.ts
  server/src/routes/asiv/payment.ts
  server/src/routes/asiv/payments.ts
  server/src/routes/asiv/public.ts
  server/src/routes/flora/users.ts
  server/src/services/asiv.ts
  server/src/services/server.ts
  server/src/utils/constants.ts
  server/src/utils/index.ts
  server/src/utils/types.ts
  server/views/index.handlebars
  server/yarn.lock
Labels: type: feature

#10 docs: Add Walkthrough for Students and Tutors
  README.md
  StudentWalkthrough.md
  TutorWalkthrough.md
  client/src/pages/flora/index.tsx
  database/init.sql
  preview/apiPayload.png
  preview/correctFlow.png
  preview/flawedFlow.png
  preview/flora.png
  preview/floraApiKey1.png
  preview/floraApiKey2.png
  preview/floraLoggedIn.png
  preview/floraLogin.png
  preview/improvedFlow.png
  preview/postman.png
  preview/targetAddress.png
  server/src/services/database.ts
Labels: status: done, type: docs

#11 fix: Fix missing slug on picture URLs
  README.md
  StudentWalkthrough.md
  TutorWalkthrough.md
Labels: type: bug

#12 feat: release prep
  README.md
  client/src/layouts/TheLayout.tsx
  client/src/pages/asiv/index.tsx
  client/src/pages/flora/index.tsx
  client/src/pages/index.tsx
Labels: status: done, type: feature
